# Generated by Django 4.2.5 on 2023-10-04 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='profile_name',
        ),
    ]
