# Generated by Django 4.2.5 on 2023-10-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0005_alter_conversation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='last_accessed',
        ),
    ]
