# Generated by Django 4.2.5 on 2023-10-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0006_remove_conversation_last_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_accessed',
            field=models.DateTimeField(null=True),
        ),
    ]
