# Generated by Django 4.2.5 on 2023-10-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0007_conversation_last_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='creation_time',
            field=models.DateTimeField(null=True),
        ),
    ]
