# Generated by Django 4.2.5 on 2023-10-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0009_interaction_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
